language: node_js
node_js: '10'

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - FORCE_COLOR=1

script:
  - yarn run prettier
  - yarn run tslint
  - yarn run build
  - yarn run typecheck
  - yarn run cover
  - ./node_modules/.bin/nyc report --reporter json
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  skip_cleanup: true
  script: yarn run semantic-release
  on:
    branch: master

branches:
  only:
    - master
    - /^renovate\/.+/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
